// Copyright (c) 2017 Computer Vision Center (CVC) at the Universitat Autonoma
// de Barcelona (UAB).
//
// This work is licensed under the terms of the MIT license.
// For a copy, see <https://opensource.org/licenses/MIT>.

#pragma once

#include "LidarDescription.generated.h"

USTRUCT()
struct CARLA_API FLidarDescription
{
  GENERATED_BODY()

  /// Number of lasers.
  UPROPERTY(EditAnywhere)
  uint32 Channels = 32u;

  /// Measure distance in centimeters.
  UPROPERTY(EditAnywhere)
  float Range = 5000.0f;

  /// Points generated by all lasers per second.
  UPROPERTY(EditAnywhere)
  uint32 PointsPerSecond = 576000u;

  /// Lidar rotation frequency.
  UPROPERTY(EditAnywhere)
  float RotationFrequency = 10.0f;

  /// Upper laser angle, counts from horizontal, positive values means above
  /// horizontal line.
  UPROPERTY(EditAnywhere)
  float UpperFovLimit = 10.0f;

  /// Lower laser angle, counts from horizontal, negative values means under
  /// horizontal line.
  UPROPERTY(EditAnywhere)
  float LowerFovLimit = -30.0f;

  /// azimuth offset of layers
  UPROPERTY(EditAnywhere)
  TArray<float> layer_azimuth{-1.400, 4.200, -1.400, 1.400, -1.400, 1.400, -4.200, 1.400, -1.400, 4.200, -1.400, 1.400, -4.200, 1.400, -4.200, 1.400, -1.400, 4.200, -1.400, 4.200, -4.200, 1.400, 1.400, 1.400, -1.400, 1.400, -1.400, 4.200, -4.200, 1.400, -1.400, 1.400};

  /// elevation of layers
  UPROPERTY(EditAnywhere)
  TArray<float> layer_elevation{-25.000, -1.000, -1.667, -15.639, -11.310, 0.000, -0.667, -8.843, -7.254, 0.333, -0.333, -6.148, -5.333, 1.333, 0.667, -4.000, -4.667, 1.667, 1.000, -3.667, -3.333, 3.333, 2.333, -2.667, -3.000, 7.000, 4.667, -2.333, -2.000, 15.000, 10.333, -1.333};

  /// Lidar range measurement noise [cm]
  UPROPERTY(EditAnywhere)
  float RangeMeasStd = 3.0f;

  /// Wether to show debug points of laser hits in simulator.
  UPROPERTY(EditAnywhere)
  bool ShowDebugPoints = false;
};
